### ISSUE TITLE
Banner image flashing on page refresh in Brave

### ISSUE THREAD

**Issue by web-padawan** [vaadin/dsp-demo#2]
## Description

Here is what happens when refreshing the page in Brave browser.

![refresh](https://user-images.githubusercontent.com/10589913/142181703-f2cdbea6-2038-4381-9421-d3ec662ccfd1.gif)

For some reason this does not happen in Chrome, Safari and Firefox 🤔

**Comment by jouni** [comment]
Can't reproduce with the latest Brave version.
<img width="702" alt="Screenshot 2023-08-08 at 10 23 40" src="https://github.com/vaadin/dsp-demo/assets/66382/661d0758-ddaa-452f-97c7-3d89aa4fb723">
